config/routes.rb
CompassTest::Application.routes.draw do
  resources :mydisks

end

app/models/mydisk.rb
class Mydisk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mydisks_controller.rb
class MydisksController < ApplicationController
  # GET /mydisks
  # GET /mydisks.json
  def index
    @mydisks = Mydisk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mydisks }
    end
  end

  # GET /mydisks/1
  # GET /mydisks/1.json
  def show
    @mydisk = Mydisk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mydisk }
    end
  end

  # GET /mydisks/new
  # GET /mydisks/new.json
  def new
    @mydisk = Mydisk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mydisk }
    end
  end

  # GET /mydisks/1/edit
  def edit
    @mydisk = Mydisk.find(params[:id])
  end

  # POST /mydisks
  # POST /mydisks.json
  def create
    @mydisk = Mydisk.new(params[:mydisk])

    respond_to do |format|
      if @mydisk.save
        format.html { redirect_to @mydisk, notice: 'Mydisk was successfully created.' }
        format.json { render json: @mydisk, status: :created, location: @mydisk }
      else
        format.html { render action: "new" }
        format.json { render json: @mydisk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mydisks/1
  # PUT /mydisks/1.json
  def update
    @mydisk = Mydisk.find(params[:id])

    respond_to do |format|
      if @mydisk.update_attributes(params[:mydisk])
        format.html { redirect_to @mydisk, notice: 'Mydisk was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @mydisk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mydisks/1
  # DELETE /mydisks/1.json
  def destroy
    @mydisk = Mydisk.find(params[:id])
    @mydisk.destroy

    respond_to do |format|
      format.html { redirect_to mydisks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mydisks_helper.rb
module MydisksHelper
end

app/views/layouts/application.html.haml
!!!
%head
  %meta{:charset => "utf-8"}
  %meta{:author => "Paul Cowan"}
  %title Lead Generator
  =stylesheet_link_tag "application"
  =javascript_include_tag "application"
  =csrf_meta_tags
%body
  .two-col

    #header
      %h1 My test Header
    #content
      %p
        Lorem ipsum dolor sit amet,
        consectetur adipisicing elit, sed do
        eiusmod tempor incididunt ut labore et
        dolore magna aliqua.
    #footer
      This is the footer.

app/views/mydisks/_form.html.haml
= form_for @mydisk do |f|
  -if @mydisk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mydisk.errors.count, "error")} prohibited this mydisk from being saved:"
      %ul
        - @mydisk.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/mydisks/edit.html.haml
%h1 Editing mydisk

= render 'form'

= link_to 'Show', @mydisk
\|
= link_to 'Back', mydisks_path

app/views/mydisks/index.html.haml
%h1 Listing mydisks

%table
  %tr
    %th
    %th
    %th

  - @mydisks.each do |mydisk|
    %tr
      %td= link_to 'Show', mydisk
      %td= link_to 'Edit', edit_mydisk_path(mydisk)
      %td= link_to 'Destroy', mydisk, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Mydisk', new_mydisk_path

app/views/mydisks/new.html.haml
%h1 New mydisk

= render 'form'

= link_to 'Back', mydisks_path

app/views/mydisks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_mydisk_path(@mydisk)
\|
= link_to 'Back', mydisks_path